### ISSUE TITLE
Fix House Cup

### ISSUE THREAD

**Issue by takouhai** [TacoWolf/WolfBot#3]
Whenever the `cup` function is called, the bot breaks if the appropriate JSON stats aren't there.

**Comment by takouhai** [comment]
stacktrace: 

```
D:\Code\tacowolf\wolfbot\commands\houses.js:233
        msg += "2. **" + helpers.housetrans(houseList[1].name) + "** with **"
                                                        ^
TypeError: Cannot read property 'name' of undefined
    at Object.module.exports.cup [as toRun] (D:\Code\tacowolf\wolfbot\commands\houses.js:233:57)
    at DiscordClient.<anonymous> (D:\Code\tacowolf\wolfbot\server.js:96:25)
    at DiscordClient.emit (events.js:118:17)
    at WebSocket.handleWSMessage (D:\Code\tacowolf\wolfbot\node_modules\discord.io\lib\index.js:205:10)
    at WebSocket.emit (events.js:110:17)
    at Receiver.ontext (D:\Code\tacowolf\wolfbot\node_modules\ws\lib\WebSocket.js:816:10)
    at D:\Code\tacowolf\wolfbot\node_modules\ws\lib\Receiver.js:477:18
    at Receiver.applyExtensions (D:\Code\tacowolf\wolfbot\node_modules\ws\lib\Receiver.js:364:5)
    at D:\Code\tacowolf\wolfbot\node_modules\ws\lib\Receiver.js:466:14
    at Receiver.flush (D:\Code\tacowolf\wolfbot\node_modules\ws\lib\Receiver.js:340:3)
```
